### ISSUE TITLE
string facets shouldn't need options

### ISSUE THREAD

**Issue by sashakames** [IS-ENES-Data/esgf-prepare#1]
Example:

cmip5 ensemble facet is listed as a string.  When I remove the "ensemble_options" I get:

Exception: "ensemble_options" or "ensemble_map" is required in section "project:cmip5"
2016/07/13 10:06:45 AM WARNING "ensemble_options" or "ensemble_map" is required in section "project:cmip5"

**Comment by glevava** [comment]
string facets shouldn't need _options list, but at least a _map to be properly declared.
Now the _pattern is also available to declare a facet though a regex.
Anyway, whatever the facet category, we should check each of them against an _options list OR a _map table OR a _pattern regex.
