### ISSUE TITLE
root directory stored in tree file in "esgprep drs"

### ISSUE THREAD

**Issue by alaniwi** [IS-ENES-Data/esgf-prepare#10]
Changing `--root` command line option does not work unless also the tree file is deleted. This should not be stored in the tree.

**Comment by glevava** [comment]
Which esgprep version are you using?
--root flag is not part of the tree file stored and so not controlled from one instance of esgprep drs to another.

**Comment by alaniwi** [comment]
It is definitely in there. Inspecting the tree file, it seems that the key is called `drs_root`, and the value is any `--tree` value which was specified, or else the current directory where the command was run.  If I do not delete the tree file, then adding/changing/removing the `--root` option has no effect when rerunning.

I am running from the HEAD of master (commit ID `b32f716`), and the reported version (with `-V`) is `v2.7.27 2017-06-12`.
