### ISSUE TITLE
use consistent delete command in "esgprep drs todo"

### ISSUE THREAD

**Issue by alaniwi** [IS-ENES-Data/esgf-prepare#14]
`esgprep drs todo` uses sometimes `rm -f` and sometimes `unlink` to remove files. (One is used for duplicate files, and the other is used for the "latest" symlink when replacing it.) You might want to be consistent.

(The calling code I am writing will accept either.)

**Comment by glevava** [comment]
Actually I didn't think there is no major difference between both regarding symlink removal.
I'll change this for "rm -f" homogeneously for duplicated files from the incoming and the "latest" symlink removal as well.
Thanks
