### ISSUE TITLE
dataset_id names 

### ISSUE THREAD

**Issue by sashakames** [IS-ENES-Data/esgf-prepare#15]
for projects whose dataset_id is configured to begin with a facet other than project, use that for creating the dataset instead of the project ID.

@sashakames may take care of this but please do if its an easy change

Such a change would mean we could roll back the behavior implemented in esg-publisher for mip_era to treat like a project.

**Comment by glevava** [comment]
What it the reason why do not treat mip_era as project?
"project" is just a facet label. The logic behind is just that a dataset ID should start with the "project ID" or "mip_era" (call it as you want) and end with the version number.
So from my point of view if we decide to treat "mip_era" as any other facet so it should be the case for "project" too and both has to be value-controlled against the INI files (which is not the current case). Define "projet" and "mip_era" in the esg.cmip6.ini has no sense, both labels are for the same facet key (the "project ID").
The main question should be to we want to impose a dataset_id starting by the "project identifier" (whatever is the name of this facet) ?

**Comment by sashakames** [comment]
Example,  input4MIPs has mip_era = CMIP6, so the dataset_id begins as CMIP6.input4MIPs....
The project == input4mips but we do not want the datasets to appear like that.  it has distinct DRS from other CMIP6.  obs4MIPs may fall under the same structure as well.

**Comment by glevava** [comment]
What I meant is that "projet" and "mip_era" refers (or should refer) to the same kind of information into the different DRS.
I don't understand what do you expect from esgprep. What should the dataset id be?
CMIP6.input4MIPs. etc.
or 
input4MIPs. etc.
??
Could you provide some usage examples with esgprep?

**Comment by glevava** [comment]
https://github.com/IS-ENES-Data/esgf-prepare/blob/b32f71604bf44724b02c52623d3a900eacd3c5cf/esgprep/mapfile/handler.py#L73 need changes to solve the issue.

**Comment by sashakames** [comment]
No longer relevant as we can continue the "project first" definition
