### ISSUE TITLE
The esg.cmip6.ini file is blank when downloaded.

### ISSUE THREAD

**Issue by William-Hill** [IS-ENES-Data/esgf-prepare#5]
The esg.cmip6.init file is populated and found at https://github.com/ESGF/config/blob/master/publisher-configs/ini/esg.cmip6.ini.

But when esgprep fetch-ini fetches the file, it's blank.  Not sure why since all other files seem to get downloaded normally.

**Comment by soay** [comment]
This is likely related to issue #6.
