### ISSUE TITLE
enhancement: sanity check esg.ini for mistakes

### ISSUE THREAD

**Issue by sashakames** [IS-ENES-Data/esgf-prepare#7]
The facet names in the dataset_id, directory_format, category list ,options, strings lists should be consistent.  While this will eventually come from a CV, the cv doesn't know about all these things.  most importantly, the dataset_id facets should be represented everywhere, or your file would most certainly have an error.  The current implementation forces me to keep re-running the mapfile generator with error each time.  Too much trial and error.

**Comment by glevava** [comment]
esgprep is based on the esg.<project>.ini provided on GitHub which follows the best practices. So if you just download them, you shouldn't need any sanity check on it. But if you locally modify the ini files, so yes you could have several try/error session before to have esgprep working well... but that's not recommended.
Anyway in a near future, esgprep will migrate all cv related feature to "pyessv" and make "esg.project.ini" usage deprecated (in the case of esgprep only for the time being).
