### ISSUE TITLE
esgprep fails to install under esgf-installer

### ISSUE THREAD

**Issue by sashakames** [IS-ENES-Data/esgf-prepare#8]
error: netCDF4 1.3.0 is installed but netCDF4<=1.2.8,>=1.2.0 is required by set(['esgprep'])

Can esgprep use 1.3.0?  I realize a new version will have to be released and so that will force an additional esgf update potentially.

**Comment by sashakames** [comment]
My mistake.  I still was testing with 2.7.19 and thought it was set to 2.7.

**Comment by sashakames** [comment]
1.2.8 doesn't seem to exist anymore in conda forge or pypi....

**Comment by sashakames** [comment]
My mistake (disregard previous delete comments) I was searching for netcdf not netcdf4.

**Comment by glevava** [comment]
netCDF4 1.3.0 and netCDF4 1.3.1 tested.
Requirements extended to netCDF4<=1.3.1,>=1.2.0.
