### ISSUE TITLE
"tree" file breaking logging in "esgprep drs"

### ISSUE THREAD

**Issue by alaniwi** [IS-ENES-Data/esgf-prepare#9]
@glevava I am confused about the logging in `esgprep drs`. It seems that some context information is saved in the "tree" file (`/tmp/DRSTree_<username>.pkl`), and I do not really understand what this is for, but it seems to break the logging on subsequent occasions that you run `esgprep drs`.

The first time that you run it, any scan errors are appended to a newly generated log file (with the date, time and process ID in the filename), and this filename is reported on standard output.

The next time, any scan errors cannot be found anywhere, although it claims (in the message on standard output) to have written them to the _same_ filename as before. It seems that this log file name is loaded from the "tree" file. This behaviour happens every time until you delete the tree file. Please could you have a look?

**Comment by glevava** [comment]
The tree file is necessary to store the results of the files scanning (in order to not redo it between subcommand actions list -> drs -> todo -> upgrade).
I checked the log is not store into the tree file. Which esgprep version are you using?

**Comment by alaniwi** [comment]
It's definitely in there for me - for example:
```
$ fgrep .err /tmp/DRSTree_<username>.pkl
sb.S'/path/to/esgprep-20171213-143359-19239.err'
```
(username and path edited here to avoid publishing system information)

Version info is the same as in #10.
